//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicnicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public string tel { get; set; }
        public string experience { get; set; }
        public byte[] picture { get; set; }
        public string preparedBy { get; set; }
    }
}
