//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicnicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class hatlar
    {
        public int Id { get; set; }
        public string name { get; set; }
        public System.Data.Spatial.DbGeometry guzergah { get; set; }
        public string capacity { get; set; }
        public string preparedBy { get; set; }
    }
}
