//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicnicProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class piknik_7_mayisEntities : DbContext
    {
        public piknik_7_mayisEntities()
            : base("name=piknik_7_mayisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<davetliler> davetlilers { get; set; }
        public DbSet<driver> drivers { get; set; }
        public DbSet<hatlar> hatlars { get; set; }
        public DbSet<malzemeListesi> malzemeListesis { get; set; }
        public DbSet<marketler> marketlers { get; set; }
        public DbSet<organizasyonListesi> organizasyonListesis { get; set; }
        public DbSet<piknik_yerleri> piknik_yerleri { get; set; }
    }
}
