//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicnicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class organizasyonListesi
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public System.Data.Spatial.DbGeography location { get; set; }
        public string job { get; set; }
        public byte[] picture { get; set; }
        public string preparedBy { get; set; }
    }
}
